### ISSUE TITLE
Implement exit with no options

### ISSUE THREAD

**Issue by liocle** [mxafi/minishell#27]

**Comment by liocle** [comment]
In bash, if exit exits properly, it retains the previous input exit code and outputs it instead of 0. If exit itself exits wrongly, it provides its own error exit code.

bash-3.2$ cd asgsadg
bash: cd: asgsadg: No such file or directory
bash-3.2$ exit
exit
c3r3p6 :: Documents/__minishell_____/minishell ‹toto*› % expr $?             1 ↵
1
c3r3p6 :: Documents/__minishell_____/minishell ‹ltoto*› % bash
bash-3.2$ echo hello
hello
bash-3.2$ exit
exit
c3r3p6 :: Documents/__minishell_____/minishell ‹toto*› % expr $?
0

**Comment by liocle** [comment]
exit status should handle as well exit +/- values just as atoi does:
``` 
ash-3.2$ bash
bash-3.2$ exit -2
exit
bash-3.2$ echo $?
254
bash-3.2$ bash
bash-3.2$ exit -10
exit
bash-3.2$ echo $?
246
bash-3.2$ bash
bash-3.2$ exit 20
exit
bash-3.2$ echo $?
20
bash-3.2$

**Comment by mxafi** [comment]
done
