### ISSUE TITLE
Lexer is mislabeling CMD and ARG when redirectors before command

### ISSUE THREAD

**Issue by mxafi** [mxafi/minishell#41]
<img width="366" alt="bug-mislabeled" src="https://github.com/mxafi/minishell/assets/95432159/9f8d0f8d-89bd-4793-9c52-32e2b1f07a3f">

Environment: M1 Macbook Air

**Comment by liocle** [comment]
Fixed, but noticed root leaks that I dont have time to investigate now
```bash
shellfish🦞> <toto cat >tata
shellfish🦞> cat tata
tutuu
shellfish🦞>
`

**Comment by mxafi** [comment]
fixed, leaks fixed as well
